version: "3.3"
services:

  php1:
    container_name: php-apache1
    build: ./php
    volumes:
      - ./src/mysql1.php:/var/www/html/index.php
      - ./src/testdb.php:/var/www/html/testdb.php
    links:
      - mysql
    ports:
      - 8081:80

  php2:
    container_name: php-apache2
    build: ./php
    volumes:
      - ./src/mysql2.php:/var/www/html/index.php
      - ./src/testdb.php:/var/www/html/testdb.php
    links:
      - mysql
    ports:
      - 8082:80

  php3:
    container_name: php-apache3
    build: ./php
    volumes:
      - ./src/mysql3.php:/var/www/html/index.php
      - ./src/testdb.php:/var/www/html/testdb.php
    links:
      - mysql
    ports:
      - 8083:80

#DB Server
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_DATABASE: dbtest
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: passworduser

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpadm
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80

#Load Balancer
  lb:
    restart: always
    build: ./lbserver
    container_name: lbserver
    ports:
      - "80:80"


#Monitoring
  prometheus:
    restart: unless-stopped
    image: bitnami/prometheus
    container_name: prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--web.enable-lifecycle'

  mysql-exporter:
    restart: unless-stopped
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: root:passwordroot@(mysql:3306)

#secrets:
#   db_password:
#     file: /data/mysql/db_password.txt
#   db_root_password:
#     file: /data/mysql/db_root_password.txt
