---
- name: Setup git configuration
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "vmkolev" }
    - {name: "user.email", value: "kolevvm@gmail.com" }
    - {name: "ui.color",   value: "True" }
  become: true